# Path: .github\workflows\deploy.yml
# generate a nodejs workflow file
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Pterodactyl & Restart Server
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.PANEL_URL }}api/client/servers/${{ secrets.PANEL_ID }}/power
          method: POST
          bearerToken    : ${{ secrets.API_KEY }}
          data: '{ "signal": "restart" }'

