name: publish
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/neongamerbot-qk/crc:latest
          docker push ghcr.io/neongamerbot-qk/crc:latest
